{% set version = "3.0.13" %}

package:
  name: simpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simpy/simpy-{{ version }}.tar.gz
  sha256: dd8c16ca3cff1574c99fe9f5ea4019c631c327f2bdc842e8b1a5c55f5e3e9d27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools_scm
  run:
    - python >=2.7

test:
  source_files:
    - tests
  imports:
    - simpy
    - simpy.resources
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - pytest-benchmark
    - pytest-cov

about:
  home: https://simpy.readthedocs.io
  summary: Event discrete, process based simulation for Python.
  license: MIT
  license_file: LICENSE.rst
  dev_url: https://gitlab.com/team-simpy/simpy
  doc_url: https://simpy.readthedocs.io
  doc_source_url: https://gitlab.com/team-simpy/simpy/-/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - bollwyvl
